# Generated by Django 3.2.8 on 2021-10-29 16:36

from django.db import migrations

import marion.fields


class Migration(migrations.Migration):
    dependencies = [
        ("marion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentrequest",
            name="issuer",
            field=marion.fields.IssuerLazyChoiceField(
                help_text="The issuer of the document among allowed ones",
                max_length=200,
                verbose_name="Issuer",
            ),
        ),
    ]
