# Generated by Django 3.2 on 2021-06-29 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssuerChoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issuer_path",
                    models.TextField(
                        help_text="Full dot-notation path to the issuer class. e.g.: 'apps.shop.issuers.invoice.InvoiceDocument'",
                        unique=True,
                        verbose_name="Issuer Path",
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=100, unique=True, verbose_name="Label"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="documentrequest",
            name="issuer",
            field=models.ForeignKey(
                help_text="The issuer of the document among allowed ones",
                on_delete=django.db.models.deletion.CASCADE,
                to="marion.issuerchoice",
                verbose_name="Issuer",
            ),
        ),
    ]
