# Generated by Django 3.1 on 2020-09-10 14:53

from django.db import migrations, models

import marion.documents.models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentrequest",
            name="context",
            field=marion.documents.models.PydanticModelField(
                blank=True,
                editable=False,
                help_text="Context used to render the document's template",
                null=True,
                verbose_name="Collected context",
            ),
        ),
        migrations.AlterField(
            model_name="documentrequest",
            name="context_query",
            field=marion.documents.models.PydanticModelField(
                help_text="Context will be fetched from those parameters",
                verbose_name="Context query parameters",
            ),
        ),
        migrations.AlterField(
            model_name="documentrequest",
            name="issuer",
            field=models.CharField(
                choices=[("howard.issuers.RealisationDocument", "Realisation")],
                help_text="The issuer of the document among allowed ones",
                max_length=200,
                verbose_name="Issuer",
            ),
        ),
    ]
